### ISSUE TITLE
Metadata page including HCLS stats

### ISSUE THREAD

**Issue by AlasdairGray** [AlasdairGray/IDP-KG#21]
Use a script to execute the HCLS queries in order and generate a static page containing the results. 

Before the result of each query, put the query description. 

Generated page should be compatible with GitHub pages and include version metadata about the IDP-KG (I'm thinking we'll have a new page when we have a new version).

We don't want the page dynamically generated as the purpose is to provide the statistics without impacting the SPARQL endpoint.

**Comment by AlasdairGray** [comment]
Related to #14

**Comment by AlasdairGray** [comment]
@ImranAsif48 I've created pages about two versions of the KG. Can you add the basic HCLS stats about each of them as Markdown tables with suitable headings?

**Comment by ImranAsif48** [comment]
@AlasdairGray Yes I can do it. Where can I find the stats?

**Comment by ImranAsif48** [comment]
@AlasdairGray I need to execute the queries from the https://github.com/AlasdairGray/IDP-KG/tree/main/queries/hcls-stats folder and make the table in GitHub Page (https://alasdairgray.github.io/IDP-KG/versions/idp-kg_2021-09-28).

Did I get it right?

**Comment by AlasdairGray** [comment]
We're looking to have something like this [Bio2RDF ChEMBL page](https://download.bio2rdf.org/files/release/3/chembl/chembl.html). For now, I think it would suffice to have the Basic Metrics and the Types count. This should be done for both versions.

You'll need to put the data into the corresponding md file after the final `---`.

**Comment by ImranAsif48** [comment]
@AlasdairGray I added the stats on the both versions. Please check it.

Thanks
