### ISSUE TITLE
Formatting of results in notebook

### ISSUE THREAD

**Issue by AlasdairGray** [AlasdairGray/IDP-KG#22]
When using the analysis notebook on [mybinder](https://mybinder.org/v2/gh/AlasdairGray/IDP-KG/HEAD?labpath=notebooks%2FAnalysisQueries.ipynb) the results are offset to the right with some queries, e.g. Minimal protein information query, see screenshot below.

@ImranAsif48 is this something to do with the CSS or the fact that this is running as a jupyter-lab rather than plain jupyter notebook?

![Screenshot 2022-01-07 at 13 42 28](https://user-images.githubusercontent.com/1141265/148552334-ef6de601-c962-4132-a51b-87e835fb29db.png)

**Comment by ImranAsif48** [comment]
@AlasdairGray I just fixed the bug in CSS. Please check it.

**Comment by ImranAsif48** [comment]
@AlasdairGray I also checked on binder it will be look good now.

![image](https://user-images.githubusercontent.com/52410211/148584535-8b133b62-c70a-4b11-aa5d-6af4bd772c68.png)

**Comment by AlasdairGray** [comment]
> @AlasdairGray I just fixed the bug in CSS. Please check it.

Thanks, I've also copied this fix into the https://github.com/BioSchemas/bioschemas-data-harvesting notebook :)

**Comment by ImranAsif48** [comment]
> 
> Thanks, I've also copied this fix into the https://github.com/BioSchemas/bioschemas-data-harvesting notebook :)

@AlasdairGray You should need to copy custom.css file into https://github.com/BioSchemas/bioschemas-data-harvesting repository because I looked at the css file it doesn't seem same.
